all:
  hosts:
    malachor.mcru.pink:
      ansible_host: malachor.mcru.pink
      ansible_become_password: "{{ ansible_user_pass }}"
    localhost:
      ansible_become_password: "{{ ansible_user_pass }}"
      vars:
        ansible_connection: local
        ansible_host: localhost
